services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: haproxy_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  
  otel-collector:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-tracing
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped

  nginx-helloworld:
    image: nginx:alpine
    container_name: nginx-helloworld
    volumes:
      - "./haproxy/nginx-helloworld.html:/usr/share/nginx/html/index.html:ro"
    ports:
      - "8081:80"
    restart: always

  haproxy:
    image: haproxy:3.3-alpine
    volumes:
      - ./haproxy/conf.d:/usr/local/etc/haproxy/conf.d:ro
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/conf.d/"]
    ports:
      - "8080:8080"
      - "127.0.0.1:8404:8404"
    depends_on:
      - nginx-helloworld

  # backend:
  #   image: oven/bun:alpine
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: bun dev:backend
  #   ports:
  #     - "3000:3000"

  # frontend:
  #   image: oven/bun:alpine
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: bun dev:frontend
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend

volumes:
  redis_data: